version = "3.8.3"
runner.dialect = scala3

maxColumn = 100
align.preset = more
newlines.topLevelStatements = [before,after]

docstrings.style = Asterisk
docstrings.wrap = no

rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]

indent.main = 2
indent.significant = 2