package monad_core.simulator.infrastructure.ai.agent_evaluator

import dev.langchain4j.model.chat.ChatModel
import dev.langchain4j.service.{AiServices, SystemMessage, UserMessage, V}
import monad_core.simulator.application.engine.world.World
import monad_core.simulator.domain.ai.agent_evaluation.{AgentEvaluationResult, AgentEvaluationTest}
import monad_core.simulator.errors.BaseError
import monad_core.simulator.infrastructure.ai.Langchain4jToolResponse.{
  renderEntity,
  renderSurface,
  renderTeam
}

import scala.beans.BeanProperty
import scala.util.Try

/**
 * Mutable JavaBean populated by LangChain4j from the judge model response.
 * the bean property are reuired because LangChain4j work with Java classes
 */
class Langchain4jAgentEvaluationResult:
  /** Whether the response used the expected language. */
  @BeanProperty var correctLanguageChoose: Boolean = false

  /** Language grammar and clarity score in `[0, 100]`. */
  @BeanProperty var languageCorrectness: Int = 0

  /** Whether the response and final world satisfy the expectation. */
  @BeanProperty var expectationMaintained: Boolean = false

/** LangChain4j service contract for the model that judges an evaluation conversation. */
trait Langchain4jAgentEvaluationJudgeAssistant:

  @SystemMessage(
    Array(
      "You evaluate an AI assistant for the MonadCore2D scene editor.",
      "correctLanguageChoose is true only when the response uses the expected language.",
      "languageCorrectness measures grammar and clarity in the expected language (is an integer between 0 and 100).",
      "expectationMaintained is true only when the response and final world satisfy the stated expectation."
    )
  )
  @UserMessage(
    Array(
      "Expected language: {{expectedLanguage}}",
      "User prompts in conversation order:",
      "{{userPrompts}}",
      "Expected outcome: {{expectedOutcome}}",
      "Assistant responses in conversation order:",
      "{{assistantResponses}}",
      "Final world entities:",
      "{{entities}}",
      "Final world surfaces:",
      "{{surfaces}}",
      "Final world teams:",
      "{{teams}}"
    )
  )
  /**
   * The Ai model Judge evaluate the AI agent actions.
   *
   * @param expectedLanguage expected response language
   * @param userPrompts ordered user prompts
   * @param expectedOutcome expected final result
   * @param assistantResponses ordered assistant responses
   * @param entities rendered final entities
   * @param surfaces rendered final surfaces
   * @param teams rendered final teams
   * @return values generated by the judge model
   */
  def evaluate(
      @V("expectedLanguage") expectedLanguage: String,
      @V("userPrompts") userPrompts: String,
      @V("expectedOutcome") expectedOutcome: String,
      @V("assistantResponses") assistantResponses: String,
      @V("entities") entities: String,
      @V("surfaces") surfaces: String,
      @V("teams") teams: String
  ): Langchain4jAgentEvaluationResult

/**
 *  Raised when the judge has not provided a valid response or is unavailable
 *
 * @param reason description of an invalid or unavailable judge response
 */
case class InvalidAgentEvaluationJudgement(reason: String)
    extends BaseError(s"Invalid agent evaluation judgement: $reason")

/**
 * Validated measurements produced by the judge model.
 *
 * @param correctLanguageChoose whether the expected language was selected
 * @param languageCorrectness validated language quality score
 * @param expectationMaintained whether the expected outcome was satisfied
 */
case class Langchain4jAgentEvaluationJudgement(
    correctLanguageChoose: AgentEvaluationResult.Bool,
    languageCorrectness: AgentEvaluationResult.Score,
    expectationMaintained: AgentEvaluationResult.Bool
)

/** @param assistant LangChain4j judge service used to evaluate conversations */
case class Langchain4jAgentEvaluationJudge(
    assistant: Langchain4jAgentEvaluationJudgeAssistant
):

  /**
   * Renders the test context, invokes the judge model, and returns its scores.
   *
   * @param test the test description
   * @param agentResponses ordered responses from the tested agent
   * @param finalWorld world state after the conversation
   * @return validated judgement, or an error when generation or conversion from judgement to scores fails
   */
  def evaluate(
      test: AgentEvaluationTest,
      agentResponses: Seq[String],
      finalWorld: World
  ): Either[BaseError, Langchain4jAgentEvaluationJudgement] =
    for
      judgement <- Try {
        assistant.evaluate(
          expectedLanguage = test.language.toString,
          userPrompts = renderMessages(test.prompts),
          expectedOutcome = test.expectation,
          assistantResponses = renderMessages(agentResponses),
          entities = render(finalWorld.getAllEntities)(renderEntity),
          surfaces = render(finalWorld.getAllSurfaces)(renderSurface),
          teams = render(finalWorld.getAllTeams)(renderTeam)
        )
      }.toEither.left.map(error => InvalidAgentEvaluationJudgement(error.getMessage))
      languageScore <- AgentEvaluationResult.fromScore(judgement.languageCorrectness)
    yield Langchain4jAgentEvaluationJudgement(
      correctLanguageChoose = AgentEvaluationResult.fromBool(judgement.correctLanguageChoose),
      languageCorrectness = languageScore,
      expectationMaintained = AgentEvaluationResult.fromBool(judgement.expectationMaintained)
    )

  private def render[A](values: List[A])(renderer: A => String): String =
    if values.isEmpty then "none"
    else values.map(renderer).mkString("\n---\n")

  private def renderMessages(messages: Seq[String]): String =
    if messages.isEmpty then "none"
    else
      messages.zipWithIndex
        .map: (message, index) =>
          s"${index + 1}: $message"
        .mkString("\n")

/** Factory for [[Langchain4jAgentEvaluationJudge]]. */
object Langchain4jAgentEvaluationJudge:

  /**
   * Build an [[Langchain4jAgentEvaluationJudge]]
   *
   * @param chatModel model used as judge
   * @return configured evaluation judge
   */
  def build(chatModel: ChatModel): Langchain4jAgentEvaluationJudge =
    val assistant = AiServices
      .builder(classOf[Langchain4jAgentEvaluationJudgeAssistant])
      .chatModel(chatModel)
      .build()

    Langchain4jAgentEvaluationJudge(assistant)
