name: release.yml
on:
  push:
    branches:
      - main
      - f/ci-cd-pipeline
  pull_request:
    branches:
      - main
jobs:
  generate-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build Fat JAR
        run: sbt assembly

      - name: Install Quarkdown
        run: curl -fsSL https://raw.githubusercontent.com/quarkdown-labs/get-quarkdown/refs/heads/main/install.sh | sudo env "PATH=$PATH" bash

      - name: Generate PDF Documentation
        run: quarkdown c docs/main.qd --pdf --out-name="documentation"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target/out/jvm/scala-3.8.4/monadcore2d/MonadCore2D-assembly-**.jar
            quarkdown-output/documentation.pdf