name: scala-tests.yml
on:
  push:
    branches:
      # run on any branch
      #- main
      #- development
  pull_request:
    branches:
      - main
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and sbt Cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run unit and integration tests
        run: sbt test
